name: Daily Refresh Streamlit App

on:
  schedule:
    - cron: '0 11 * * *'  # Runs every day at 7:00 AM Eastern (11:00 UTC)
  workflow_dispatch:

jobs:
  touch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Touch app.py to force redeploy"
        run: |
          date > last_run.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last_run.txt
          git commit -m "chore: daily trigger" || echo "Nothing to commit"
          git push
